#!/usr/bin/env python3
"""Materialize advisory WorkPlan Proposal v3 for praxis-human-interface/1.

Deterministic and model-free. Every candidate, binding and relationship is parsed
from the frozen planning evidence (workplan-v3-claude.md, sections 4.2 and
6.1-6.5); every requirement id, source_ref and source_digest comes from the
TRACKED B-2 element manifest. Nothing is typed by hand and nothing is read from
/tmp or any untracked location.

Before generating, it verifies the tracked bootstrap evidence:
  B-1  goal-establish-source.json        byte-exact, sha256 == recorded ImportSourceDigest
  B-2  goal-baseline-elements.json       equals the deterministic regeneration from B-1
  B-3  goal-stored-order-attestation.json binds B-1, B-2, the tracked read-only
                                          inspect capture and the stored element order
It then requires the generated bytes to equal the proposal file recorded in B-3.

Usage:
  materialize_proposal_v3.py [--check] [extra_output ...]

  Writes the tracked proposal (bootstrap/praxis-human-interface-proposal-v3.json)
  and any extra output paths (e.g. the operational .praxis copy). With --check it
  writes nothing and only proves the tracked proposal is reproduced exactly.
It does not invoke Praxis, a provider, or any authority operation.
"""
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bootstrap_evidence as ev  # noqa: E402

PLAN_SHA = "sha256:966d193d57d41402e414435999aaac138c4af00162101f472ec475470ae963f5"
PLAN_PATH = "docs/research/dogfood/praxis-human-interface/plans/workplan-v3-claude.md"
EXPECT = {"candidates": 23, "hard_dependency": 31, "consumer": 24, "interaction": 13, "advisory": 3}
fail, sha = ev.fail, ev.sha


def section(text, start, end):
    a = text.index(start)
    return text[a:text.index(end, a)]


def expand_bindings(cell):
    out = []
    for token in re.split(r"[,\s]+", cell.strip()):
        if not token:
            continue
        m = re.fullmatch(r"([A-Z]+)(\d+)[–-]\1(\d+)", token)
        if m:
            out += [f"{m.group(1)}{i}" for i in range(int(m.group(2)), int(m.group(3)) + 1)]
        elif re.fullmatch(r"[A-Z]+\d+", token):
            out.append(token)
        else:
            fail(f"unparseable binding token {token!r}")
    return out


def main():
    args = sys.argv[1:]
    check = "--check" in args
    extra = [a for a in args if a != "--check"]

    # 1. Tracked bootstrap evidence must verify before anything is generated.
    b1 = ev.read(ev.P["b1"])
    if sha(b1) != ev.B1_SHA:
        fail("B-1 is not the recorded establishment source")
    b2 = ev.read(ev.P["b2"])
    if b2 != ev.build_manifest(b1):
        fail("B-2 is not the deterministic regeneration of B-1")
    manifest, attestation = ev.check_b3_binding(ev.read(ev.P["b3"]))
    plan_bytes = ev.read(ev.P["plan"])
    if sha(plan_bytes) != PLAN_SHA:
        fail("planning evidence is not the frozen v3 plan")
    plan = plan_bytes.decode("utf-8")

    elements = {r["label"]: {"id": r["id"], "source_ref": f"goal:{ev.GOAL_ID}/{ev.GOAL_VERSION}#{r['kind']}/{r['stored_index']}",
                             "source_digest": r["text_sha256"]} for r in manifest["elements"]}
    if len(elements) != 31:
        fail(f"expected 31 manifest elements, found {len(elements)}")

    # 2. Candidates: plan section 4.2 table.
    table = section(plan, "### 4.2 Table", "Labels are the stored-order labels")
    rows = re.findall(r"^\| (\d+) \| (\d+) \| `([^`]+)` \| (\w+) \| ([^|]+) \|$", table, re.M)
    if len(rows) != EXPECT["candidates"]:
        fail(f"expected {EXPECT['candidates']} candidates, parsed {len(rows)}")
    order = {p: i for i, (p, _) in enumerate(ev.KINDS)}
    candidates, short = [], {}
    for pri, seq, cid, name, binds in rows:
        if name in short:
            fail(f"duplicate short name {name}")
        labels = expand_bindings(binds)
        if not labels or len(set(labels)) != len(labels):
            fail(f"{cid}: empty or duplicated bindings")
        for label in labels:
            if label not in elements:
                fail(f"{cid}: unknown element {label}")
        labels.sort(key=lambda l: (order[re.match(r"[A-Z]+", l).group()], int(re.search(r"\d+", l).group())))
        short[name] = cid
        candidates.append({
            "id": cid, "completed": False, "priority": int(pri), "sequence": int(seq),
            "source_ref": f"{PLAN_PATH}#candidate/{cid}", "source_digest": PLAN_SHA,
            "provenance": "model_proposal",
            "requirements": [dict(elements[l]) for l in labels],
        })
    candidates.sort(key=lambda c: c["sequence"])
    if [c["sequence"] for c in candidates] != list(range(1, 24)):
        fail("sequences must be exactly 1..23 and unique")
    if {r["id"] for c in candidates for r in c["requirements"]} != {e["id"] for e in elements.values()}:
        fail("candidate bindings do not cover exactly the 31 manifest elements")
    seq_of = {c["id"]: c["sequence"] for c in candidates}

    # 3. Relationships: plan sections 6.1 (hard) and 6.3-6.5.
    def edge(dep, pre, kind):
        if dep not in short or pre not in short:
            fail(f"unknown edge endpoint {dep}->{pre}")
        return {"dependent": short[dep], "prerequisite": short[pre], "kind": kind,
                "source_ref": PLAN_PATH, "source_digest": PLAN_SHA, "provenance": "model_proposal"}

    rels = []
    for line in section(plan, "### 6.1 Hard (31)", "Transitive closure").splitlines():
        m = re.match(r"^\| [\d–]+ \| ([^|]+) \| ", line)
        if not m:
            continue
        for clause in m.group(1).split(";"):
            left, right = [s.strip() for s in clause.split("→")]
            for d in [x.strip() for x in left.split(",")]:
                for p in [x.strip() for x in right.split(",")]:
                    rels.append(edge(d, p, "hard_dependency"))
    for heading, nxt, kind in [("### 6.3 Consumer (24)", "### 6.4", "consumer"),
                               ("### 6.4 Interaction (13)", "### 6.5", "interaction"),
                               ("### 6.5 Advisory (3)", "---", "advisory")]:
        for d, p in re.findall(r"`([A-Za-z]+)→([A-Za-z]+)`", section(plan, heading, nxt)):
            rels.append(edge(d, p, kind))

    counts = {k: sum(1 for r in rels if r["kind"] == k) for k in ("hard_dependency", "consumer", "interaction", "advisory")}
    for k, n in counts.items():
        if n != EXPECT[k]:
            fail(f"expected {EXPECT[k]} {k} edges, parsed {n}")
    pairs = [(r["dependent"], r["prerequisite"]) for r in rels]
    if len(set(pairs)) != len(pairs):
        fail("duplicate relationship pair")
    for r in rels:
        if seq_of[r["dependent"]] <= seq_of[r["prerequisite"]]:
            fail(f"sequence is not a linear extension of edge {r['dependent']} -> {r['prerequisite']}")
    pre = {c["id"]: set() for c in candidates}
    for r in rels:
        if r["kind"] == "hard_dependency":
            pre[r["dependent"]].add(r["prerequisite"])
    done, remaining = set(), dict(pre)
    while remaining:
        ready = [n for n, ps in remaining.items() if ps <= done]
        if not ready:
            fail("hard dependency cycle")
        for n in ready:
            done.add(n)
            del remaining[n]
    final, closure, stack = short["DOG"], set(), [short["DOG"]]
    while stack:
        for p in pre[stack.pop()]:
            if p not in closure:
                closure.add(p)
                stack.append(p)
    if closure != {c["id"] for c in candidates} - {final}:
        fail("a unit lies outside the final qualification unit's hard closure")

    proposal = {
        "BaselineID": ev.GOAL_ID, "BaselineVersion": ev.GOAL_VERSION, "ProposalVersion": "3",
        "proposal": {
            "id": f"{ev.GOAL_ID}-workplan-proposal-3",
            "proposed_by": {"id": "model:claude-sonnet-5:advisory-plan-materializer", "kind": "model"},
            "proposer_generation": "claude-sonnet-5/advisory-plan-v3@" + PLAN_SHA,
            "candidates": candidates, "relationships": rels,
        },
    }
    encoded = ev.dumps(proposal)

    # 4. The regenerated bytes must be exactly the proposal B-3 attests.
    recorded = attestation["proposal_v3_reference_check"]["proposal_file_sha256"]
    if sha(encoded) != recorded:
        fail(f"regenerated proposal {sha(encoded)} != proposal attested in B-3 {recorded}")
    tracked = ev.P["proposal"]
    if check:
        if not os.path.isfile(tracked) or ev.read(tracked) != encoded:
            fail("tracked proposal is not reproduced exactly from the tracked evidence")
    else:
        for path in [tracked] + extra:
            with open(path, "wb") as f:
                f.write(encoded)
    print(json.dumps({"mode": "check" if check else "write",
                      "candidates": len(candidates), "relationships": len(rels), **counts,
                      "requirement_refs": sum(len(c["requirements"]) for c in candidates),
                      "proposal_file_sha256": sha(encoded),
                      "outputs": [] if check else [ev.REL(tracked)] + extra}, indent=2))


if __name__ == "__main__":
    main()
